# Generated by Django 3.2 on 2022-02-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='mobile',
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('alergies', models.ManyToManyField(to='patient.Alergies')),
                ('cronic_dieseas', models.ManyToManyField(to='patient.Dieseas')),
                ('injuries', models.ManyToManyField(to='patient.Injuries')),
                ('medication', models.ManyToManyField(related_name='medication', to='patient.Medication')),
                ('past_medication', models.ManyToManyField(related_name='past_medication', to='patient.Medication')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_profile', to='patient.patientprofile')),
                ('surgeries', models.ManyToManyField(to='patient.Surgery')),
            ],
        ),
    ]
