# Generated by Django 3.2 on 2022-02-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.IntegerField(choices=[(0, 'SUPER_ADMIN'), (1, 'DOCTOR'), (2, 'PATIENT')]),
        ),
    ]
