# Generated by Django 3.2 on 2022-02-17 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_useraccount_otp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='otp_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 17, 7, 31, 14, 625270), null=True),
        ),
    ]
