# Generated by Django 3.2 on 2022-02-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0002_alter_appointments_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreviews',
            name='user_data',
        ),
        migrations.AddField(
            model_name='doctorreviews',
            name='patient_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_review', to='patient.patientprofile'),
        ),
        migrations.AlterField(
            model_name='doctorreviews',
            name='doctor_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='doctor.doctorprofile'),
        ),
    ]
