# Generated by Django 3.2 on 2022-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='daily',
            field=models.BooleanField(default=False),
        ),
    ]
