# Generated by Django 3.2 on 2022-02-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20220222_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreviews',
            old_name='doctor_data',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='doctorreviews',
            old_name='patient_data',
            new_name='patient',
        ),
    ]
