# Generated by Django 3.2 on 2022-02-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220222_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
