# Generated by Django 3.2 on 2022-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctoravailability_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
