# Generated by Django 3.2 on 2022-02-23 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0005_doctorprofile_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorSlots',
            new_name='DoctorSlot',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doctorreviews',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorreviews',
            name='patient',
        ),
        migrations.AddField(
            model_name='doctorreviews',
            name='doctor_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorreviews',
            name='user_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
