# Generated by Django 3.2 on 2022-02-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20220215_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabitily', to='doctor.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='clinic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='consultation_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='experties_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
