# Generated by Django 3.2 on 2022-02-23 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0006_auto_20220223_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorReviews',
            new_name='DoctorReview',
        ),
    ]
