# Generated by Django 3.2 on 2022-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20220215_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
