# Generated by Django 3.2 on 2022-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctorprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.DateField(blank=True, null=True),
        ),
    ]
