# Generated by Django 3.2 on 2022-02-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_doctorprofile_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='experience',
            new_name='career_started',
        ),
    ]
