# Generated by Django 3.2 on 2022-02-16 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0011_alter_doctorprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='expertise_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DoctorInfo',
        ),
    ]
