# Generated by Django 3.2 on 2022-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20220216_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='from_available',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='to_available',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='slot',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'EVENING')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='time_slot',
            field=models.ManyToManyField(to='doctor.DoctorSlots'),
        ),
    ]
