# Generated by Django 3.2 on 2022-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20220217_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslots',
            name='slot_time',
            field=models.TimeField(),
        ),
    ]
