# Generated by Django 3.2 on 2022-02-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_auto_20220217_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='month',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='year',
        ),
    ]
