# Generated by Django 3.2 on 2022-02-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_auto_20220218_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
