# Generated by Django 3.2 on 2022-02-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_doctoravailability_slot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorslots',
            name='slot_time',
        ),
    ]
