# Generated by Django 3.2 on 2022-02-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_remove_doctorslots_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslots',
            name='slot_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
