# Generated by Django 3.2 on 2022-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='is_appintment',
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming'), ('CANCLE', 'Cancle')], max_length=50, null=True),
        ),
    ]
